adds target="_blank" to external links
InsaLan/frontend-insalan.fr pull request #51
Opened 2023-11-20 06:03 UTC by jasonzubiate

This change resolves #47 by adding target="_blank" to all external links found on the webpage.
Signed-off-by: Jason Zubiate <jasonzubiate.com>

2023-11-20 08:35 UTC, KwikKill requested changes
Thank you for your time, this is good but there is a slight modification required

2023-11-20 08:35 UTC, KwikKill commented on src/components/Footer.vue
> +        <a class="hover:blur-sm" href="https://www.instagram.com/insalan_officiel" target="_blank">
There is an error raised by ESlint. You should add `rel="noopener noreferrer"` when using `target="_blank"` for security reason.

2023-11-20 08:35 UTC, KwikKill commented on src/components/Footer.vue
> +        <a class="hover:blur-sm" href="https://twitter.com/insalan" target="_blank">
missing `rel="noopener noreferrer"`.

2023-11-20 08:35 UTC, KwikKill commented on src/components/Footer.vue
> +        <a class="hover:blur-sm" href="https://www.facebook.com/insalan/" target="_blank">
missing `rel="noopener noreferrer"`.

2023-11-20 08:35 UTC, KwikKill commented on src/components/Footer.vue
> +        <a class="mt-2 md:mt-5 " href="https://aeir.insa-rennes.fr" target="_blank">
missing `rel="noopener noreferrer"`.

2023-11-20 08:35 UTC, KwikKill commented on src/components/Footer.vue
> +        <a class="ml-2 mt-2 md:mt-5" href="https://insa-rennes.fr" target="_blank">
missing `rel="noopener noreferrer"`.

2023-11-20 08:35 UTC, KwikKill commented on src/components/PartnerCard.vue
> +    <a :href="partner.url" target="_blank" class="flex h-full flex-col items-center gap-2 p-2">
missing `rel="noopener noreferrer"`.

2023-11-21 06:10 UTC, jasonzubiate commented on src/components/PartnerCard.vue
> +    <a :href="partner.url" target="_blank" class="flex h-full flex-col items-center gap-2 p-2">
will add those

2023-11-21 08:58 UTC, KwikKill approved these changes
Will be merged later

2023-11-26 22:37 UTC, closed without merging